// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNKo7klmYCFFPmp6CpvECCR98CSL_n_VY',
    appId: '1:941938625190:web:7e8e0bff1ff747e1c10267',
    messagingSenderId: '941938625190',
    projectId: 'mydrive-7020b',
    authDomain: 'mydrive-7020b.firebaseapp.com',
    storageBucket: 'mydrive-7020b.firebasestorage.app',
    measurementId: 'G-ZRY5GWK6DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY75A1DD9kAUlUz3PBqXr_Nql0w-uh7SA',
    appId: '1:941938625190:android:ff9c733bd3e3662bc10267',
    messagingSenderId: '941938625190',
    projectId: 'mydrive-7020b',
    storageBucket: 'mydrive-7020b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2d66knZQPMh4y3ZutriS7kz_D7SbuG4M',
    appId: '1:941938625190:ios:c5b5d61afa0be945c10267',
    messagingSenderId: '941938625190',
    projectId: 'mydrive-7020b',
    storageBucket: 'mydrive-7020b.firebasestorage.app',
    iosBundleId: 'com.example.mydrive',
  );
}
